requirejs.config({
	paths:{
		'jquery':'lib/jQuery/jquery.min',
		//'jquery':'https://code.jquery.com/jquery-3.1.1.slim.min',
		'jqueryui':'lib/jQuery/jqueryui',
		'css':'lib/RequireJS/css.min',
		'Vue':'lib/Vue/vue',
		'WdatePicker':'lib/My97DatePicker/WdatePicker',
	},
	shim:{
		WdatePicker:{
			exports:'WdatePicker'
		}
	}
});